#!/bin/bash

set -e

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Setup: For Coding Agents"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Check for .env file
if [ ! -f ".env" ]; then
    echo "⚠️  No .env file found!"
    echo ""
    echo "Creating .env from template..."
    cp .env.example .env
    echo "✓ Created .env"
    echo ""
    echo "Please edit .env and add your API keys, then run setup again:"
    echo "  nano .env"
    echo ""
    exit 1
fi

# Load environment variables from .env
echo "Loading environment variables from .env..."
set -a
source .env
set +a

# Define required environment variables
REQUIRED_VARS=("PARALLEL_API_KEY")

# Check if all required variables are set
MISSING_VARS=()
for var in "${REQUIRED_VARS[@]}"; do
    if [ -z "${!var}" ] || [ "${!var}" = "your-api-key-here" ]; then
        MISSING_VARS+=("$var")
    fi
done

if [ ${#MISSING_VARS[@]} -gt 0 ]; then
    echo "⚠️  Missing or placeholder values in .env:"
    for var in "${MISSING_VARS[@]}"; do
        echo "  - $var"
    done
    echo ""
    echo "Please edit .env and add your actual API keys:"
    echo "  nano .env"
    echo ""
    exit 1
fi

echo "✓ All required environment variables are set"
echo ""

# Update ~/.bashrc with environment variables (for interactive shells)
echo "Updating ~/.bashrc..."
BASHRC="$HOME/.bashrc"
touch "$BASHRC"

# Remove old entries for these variables to avoid duplicates
for var in "${REQUIRED_VARS[@]}"; do
    sed -i.bak "/^export $var=/d" "$BASHRC"
done

# Append new entries
echo "" >> "$BASHRC"
echo "# For Coding Agents - Auto-generated by setup.sh" >> "$BASHRC"
for var in "${REQUIRED_VARS[@]}"; do
    echo "export $var='${!var}'" >> "$BASHRC"
done

echo "✓ Updated ~/.bashrc (for interactive shells)"
echo "✓ Tools will read .env directly (Pi uses 'sh -c' which doesn't load profiles)"
echo ""

# Make all tools executable
echo "Making tools executable..."
chmod +x tools/*.js

# Create wrapper scripts in ~/.local/bin with "tool-" prefix
echo "Installing CLI tools to ~/.local/bin..."
mkdir -p "$HOME/.local/bin"
for script in tools/*.js; do
    if [ -f "$script" ]; then
        TOOL_NAME=$(basename "$script" .js)
        WRAPPER="$HOME/.local/bin/tool-$TOOL_NAME.js"
        ACTUAL_TOOL="$(pwd)/$script"
        
        # Create wrapper that sets env vars and execs the real tool
        cat > "$WRAPPER" << EOF
#!/bin/sh
# Auto-generated wrapper by setup.sh
# Sets environment variables and executes the actual tool

# Export all required environment variables
$(for var in "${REQUIRED_VARS[@]}"; do
    echo "export $var='${!var}'"
done)

# Execute the actual tool
exec "$ACTUAL_TOOL" "\$@"
EOF
        
        chmod +x "$WRAPPER"
        echo "✓ tool-$TOOL_NAME.js (wrapper created)"
    fi
done

# Copy pi/ structure to ~/.pi/ (Pi doesn't support symlinks)
if [ -d "pi" ]; then
    echo ""
    echo "Setting up Pi agent files..."
    cd pi
    find . -type f -name "*.md" | while read -r file; do
        TARGET_DIR="$HOME/.pi/$(dirname "$file")"
        mkdir -p "$TARGET_DIR"
        cp "$file" "$TARGET_DIR/$(basename "$file")"
        echo "✓ ~/.pi/$file (copied)"
    done
    cd ..
fi

# Copy opencode/ structure to ~/.config/opencode/
if [ -d "opencode" ]; then
    echo ""
    echo "Setting up OpenCode agent files..."
    cd opencode
    find . -type f -name "*.md" | while read -r file; do
        TARGET_DIR="$HOME/.config/opencode/$(dirname "$file")"
        mkdir -p "$TARGET_DIR"
        cp "$file" "$TARGET_DIR/$(basename "$file")"
        echo "✓ ~/.config/opencode/$file (copied)"
    done
    cd ..
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  ✅ Setup complete!"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Source .bashrc to refresh environment in current shell
source "$HOME/.bashrc"

echo "Available commands:"
for script in tools/*.js; do
    if [ -f "$script" ]; then
        echo "  tool-$(basename "$script")"
    fi
done
echo ""
echo "Environment variables loaded. Try it out:"
echo "  tool-parallel-search.js \"quantum computing\""
echo ""
